//problem12.cpp: this file contains the function for the solution for problem 12

/*
* The sequence of triangle numbers is generated by adding the natural numbers. So the 7th 
* triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
* 1, 3, 6, 10, 15, 21, 28, 36, 45, 55
* 
* If we list the factors of the first seven triangle numbers, we can see that 28 is the first
* triangle number to have over five divisors.
* 
* What is the value of the first triangle number to have over five hundred divisors? 
* 
* Solution: 76576500
* Time: 420 ms
*/

#include "kmath.h"

long problem12()
{
	long target{ 0 };
	for (long i = 1;; ++i)
	{
		target += i;
		if (kmath::numDivisors(target) > 500) return target;
	}
}